name: game
resolution: workspace
description: Game package containing domain, data, and presentation layers for Tic-Tac-Toe
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.3
  build_runner: ^2.4.13
